wake_word_confidence: 0.75
TTS_server_IP: "192.168.1.185"
TTS_server_port: 5000
STT_server_IP: "192.168.1.185"
STT_server_port: 5000
wake_word_models: ["Sudo.onnx", "Suto.onnx"]
Input_device: 6
Output_device: 6
notification_sound: "default.wav"
silence_time: 3